Cuestión 4: Se realiza un estudio para determinar si cierto
tratamiento tiene algún efecto sobre la cantidad de metal que
se elimina en una operación de encurtido. Una muestra aleatoria
de 100 piezas se sumerge en un baño por 24 horas sin el tratamiento, 
lo que produce un promedio de 12.2 milímetros de metal eliminados y una
desviación estándar muestral de 1.1 milímetros. Una segunda muestra de 
200 piezas se somete al tratamiento, seguido de 24 horas de inmersión en 
el baño, lo que da como resultado una eliminación promedio de 9.1 milímetros
de metal, con una desviación estándar muestral de 0.9 milímetros. 

a) Calcular un estimado del intervalo de confianza del 98% para la diferencia
entre las medias de las poblaciones.  

b) Analizar según los datos si el tratamiento reduce o no la cantidad media del
metal eliminado. Razonar adecuadamente la respuesta

```{r}
# a) y b)
# Muestra 1 (SIN TRATAMIENTO)
n1=100
media1=12.2 #mm
desviacion_tipica1=1.1 #mm

# Muestra 2 (CON TRATAMIENTO)
n2=200
media2=9.1 #mm
desviacion_tipica2=0.9 #mm
# Se trata de un intervalo de confianza para la diferencia de 
# medias con varianzas desconocidas

# 1) Haremos un contraste para la igualdad de varianzas

# H0= varianza1^2=varianza2^2 ( IGUALES)
# H1= varianza1^2 /= varianza2^2 (DISTINTOS)
# Se trata de una fisher
alfa=0.02
alfa2=alfa/2
alfa1=1-alfa+alfa2
v1=n1-1
v1
v2=n2-1
v2
qf(alfa1,v1,v2)
qf(alfa2,v1,v2)
# Ahora vamos ha hacer el estadistico de contraste
#  f = Si^2/Si2^2
f=(desviacion_tipica1^2)/(desviacion_tipica2^2)
f
# Decision: No aceptamos H0
# No podemos asumir la igualdad de varianzas
# -----) Por lo tanto el intervalo de confianza para la 
# diferencia de medias mu1-mu2 con varianza 1 y varianza 2 desconocidas y distintas
v=((((desviacion_tipica1^2)/n1))+((desviacion_tipica2^2)/n2))^2/
  (((((desviacion_tipica1^2)/n1)^2)/(n1-1))+((((desviacion_tipica2^2)/n2)^2)/(n2-1)))
v
# Y para hallar los intervalos es:
# media1-media2+-v*sqrt(s1^2/n1+s2^2/n2)
Intervalo1=(media1-media2)+v*alfa2*sqrt(desviacion_tipica1^2/n1+desviacion_tipica2^2/n2)
Intervalo1
Intervalo2=(media1-media2)-v*alfa2*sqrt(desviacion_tipica1^2/n1+desviacion_tipica2^2/n2)
Intervalo2
# Estimamos mU1>mu2  
# Ademas hacemos el estadistico
t=(media1-media2)/sqrt((desviacion_tipica1^2/n1)+(desviacion_tipica2/n2))
t
# Con todo esto deducimos que la muestra sin tratamiento hace mas efecto a la 
#cantidad de metal eliminado.Entonces si se deuce que el tratamiento esta 
# reduciendo la cantidad de metal eliminado.
```

